import { Event } from './types/events';

export const events: Event[] = [
  {
    id: 1,
    eventName: 'Team Meeting',
    description: 'Quarterly planning session',
    date: '2025-04-05',
    startTime: '10:00',
    endTime: '11:30',
    schoolName: 'Grimsley High School',
    county: 'Guilford',
  },
  {
    id: 2,
    eventName: 'Client Call',
    description: 'Project update with client',
    date: '2025-04-06',
    startTime: '14:00',
    endTime: '15:00',
    schoolName: 'Page High School',
    county: 'Guilford',
  },
  {
    id: 3,
    eventName: 'Workshop',
    description: 'Frontend optimization techniques',
    date: '2025-04-07',
    startTime: '09:00',
    endTime: '12:00',
    schoolName: 'Northwest Guilford High School',
    county: 'Guilford',
  },
  {
    id: 4,
    eventName: 'Design Review',
    description: 'UI/UX feedback session',
    date: '2025-04-08',
    startTime: '13:00',
    endTime: '14:30',
    schoolName: 'Northern Guilford High School',
    county: 'Guilford',
  },
  {
    id: 5,
    eventName: 'Marketing Sync',
    description: 'Weekly collaboration with marketing team',
    date: '2025-04-09',
    startTime: '11:00',
    endTime: '11:45',
    schoolName: 'Southeast Guilford High School',
    county: 'Guilford',
  },
  {
    id: 6,
    eventName: 'Code Review',
    description: 'Review PRs from the week',
    date: '2025-04-10',
    startTime: '16:00',
    endTime: '17:00',
    schoolName: 'Southern Guilford High School',
    county: 'Guilford',
  },
  {
    id: 7,
    eventName: 'Sprint Planning',
    description: 'Plan tasks for next sprint',
    date: '2025-04-11',
    startTime: '10:00',
    endTime: '11:30',
    schoolName: 'Western Guilford High School',
    county: 'Guilford',
  },
  {
    id: 8,
    eventName: 'Product Demo',
    description: 'Demonstrate new features to stakeholders',
    date: '2025-04-12',
    startTime: '15:00',
    endTime: '16:00',
    schoolName: 'Eastern Guilford High School',
    county: 'Guilford',
  },
  {
    id: 9,
    eventName: 'Hackathon',
    description: 'Internal team innovation day',
    date: '2025-04-13',
    startTime: '08:00',
    endTime: '17:00',
    schoolName: 'Ben L. Smith High School',
    county: 'Guilford',
  },
  {
    id: 10,
    eventName: 'One-on-One',
    description: 'Monthly check-in with manager',
    date: '2025-04-14',
    startTime: '09:30',
    endTime: '10:00',
    schoolName: 'High Point Central High School',
    county: 'Guilford',
  },
];
